### ISSUE TITLE
时不时会自动切换为全局模式

### ISSUE THREAD

**Issue by zackandyou** [jc3213/easy_proxy#2]
手动切换为智能模式后，隔一段时间就会切换为全局模式

**Comment by jc3213** [comment]
基于Manifest V3的`ServiceWorker`会在30秒内无任何活跃数据的时候自动休眠，然后再次唤醒后只能重新读取储存。如果你之前的设置就是智能模式，那么理论上应该没问题才对。

或者你可以等待升级1.1.1版本后，试试打开设置里的`常驻后台`功能。（需要等待Edge商城审核通过才能得到推送，已经审核好几天了）

**Comment by jc3213** [comment]
1.1.0确实存在bug但应该不至于出现你说的问题？可以的话给我看一下后台的错误记录吧。


![1](https://github.com/user-attachments/assets/69b0ea5c-3aa6-4a84-a53e-e3612df94cfb)
我自己的测试是，改成**全局**或者**智能**，也会在`ServiceWorker`休眠时恢复成**智能**，但也只是如此显示，并不会影响实际功能。当然因为本地源代码已经是1.1.1了，我个人推荐你稍微等待一下。

**Comment by jc3213** [comment]
@zackandyou 请问升级1.1.1后问题有解决吗？没有的话能否提供录屏方便验证？可以的话对着工具栏窗口点右键，打开控制台看看错误是什么？
